name: Spring Boot GraphQL Pipeline

on:
  push:
    branches:
      - ci/cd
  pull_request:
    branches:
      - ci/cd

jobs:
  # testing jobs
  tests:
    name: Testing application
    runs-on: ubuntu-latest
    steps:
      # clone to github env
      - name: Clone repository to local
        uses: actions/checkout@v1

      # Setup JDK
      - name: Setup JDK Enviroment
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cached maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Running mvn tests
        run: mvn test

  build:
    name: Building Docker Imager for Spring Boot GraphQL
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v1

      - name: Packaging with Maven
        run: |
          mvn package -DskipTests

      - name: Login to My Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push my Docker Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.APP_TAG }}:1.1
  publish:
    name: Publish App to Server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository to local
        uses: actions/checkout@v1

      - name: Copy env files to the server
        uses: siva1024/scp-deployer@latest
        with:
          port: 22
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_SECRET_KEY }}
          source: "./env/*"
          target: "~/Apps/irdaislakhuafa/springboot-graphql-v1.1/*"

      - name: Starting container on server
        # run: ssh -i ${{ secrets.SERVER_SECRET_KEY }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd Apps/irdaislakhuafa/springboot-graphql-v1.1 && docker-compose down && docker-compose up -d"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SECRET_KEY }}
          port: 22
          script: |
            cd Apps/irdaislakhuafa/springboot-graphql-v1.1
            docker-compose down 
            docker-compose up -d
